name: Deploy

on:
  check-run:
    types: [completed]
  branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Deploying..."
          exit 0