name: CI/CD Pipeline

on:
  pull_request: 
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v3
      - name: Deploy to production
        run: |
          # Replace this with your deployment logic
          echo "Deploying to production..."