name: CI/CD Pipeline

on:
  pull_request: 
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: print a
        run: echo printed a
      - name: print b
        run: echo printed b
  build2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: print c
        run: echo printed c
      - name: print d
        run: echo printed d