name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          echo "Running tests..."
          exit 0
      - name: Create check run
        uses: actions/create-check-run@v2
        with:
          name: Build and Test Check
          head_sha: ${{ github.sha }}
          status: completed
          conclusion: success